const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const Sentiment = require('sentiment');
const { generatePaletteFromSentiment } = require('./colorEngine');

const app = express();
const sentiment = new Sentiment();
const PORT = process.env.PORT || 3001;

// Middleware
app.use(helmet());
app.use(cors());
app.use(express.json());

// Routes
app.get('/api/health', (req, res) => {
  res.json({ 
    status: 'healthy', 
    message: 'Synth API - Synesthesia as a Service',
    version: '0.1.0'
  });
});

// Main endpoint: text to color palette
app.post('/api/synth/text-to-colors', (req, res) => {
  try {
    const { text, options = {} } = req.body;
    
    if (!text || typeof text !== 'string') {
      return res.status(400).json({ 
        error: 'Text input required',
        example: { text: "I feel creative and energetic!" }
      });
    }

    // Analyze sentiment
    const analysis = sentiment.analyze(text);
    
    // Generate color palette
    const palette = generatePaletteFromSentiment(analysis, text, options);
    
    res.json({
      success: true,
      input: text,
      sentiment: {
        score: analysis.score,
        comparative: analysis.comparative,
        tokens: analysis.tokens,
        words: analysis.words,
        positive: analysis.positive,
        negative: analysis.negative
      },
      palette,
      metadata: {
        timestamp: new Date().toISOString(),
        engine: 'synth-v0.1'
      }
    });
    
  } catch (error) {
    console.error('Error processing text:', error);
    res.status(500).json({ 
      error: 'Internal server error',
      message: error.message 
    });
  }
});

// Palette export endpoints
app.post('/api/synth/export/css', (req, res) => {
  try {
    const { palette, prefix = 'synth' } = req.body;
    
    if (!palette || !Array.isArray(palette)) {
      return res.status(400).json({ error: 'Palette array required' });
    }
    
    const cssVars = palette.map((color, index) => 
      `  --${prefix}-color-${index + 1}: ${color};`
    ).join('\n');
    
    const css = `:root {\n${cssVars}\n}`;
    
    res.json({
      success: true,
      format: 'css',
      output: css
    });
    
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.post('/api/synth/export/figma', (req, res) => {
  try {
    const { palette } = req.body;
    
    if (!palette || !Array.isArray(palette)) {
      return res.status(400).json({ error: 'Palette array required' });
    }
    
    // Convert to Figma-compatible format
    const figmaPalette = palette.map((color, index) => ({
      name: `synth-${index + 1}`,
      color: color,
      description: `Generated by Synth from emotional input`
    }));
    
    res.json({
      success: true,
      format: 'figma',
      palette: figmaPalette,
      instructions: 'Import these colors directly into your Figma color styles'
    });
    
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.listen(PORT, () => {
  console.log(`🎨 Synth API running on port ${PORT}`);
  console.log(`💫 Turning feelings into functional design palettes`);
});

module.exports = app;